services:
  web:
    image: resumescreener-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/screening/Resumescreener/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /srv/screening/Resumescreener/certs:/etc/nginx/certs:ro
    networks: [resumescreener_resumescreener_net]
